num1 =input("Enter your number1 ") 
num2 =input("Enter your number2 ")
num1 = int(num1)
num2 = int(num2)
print(num1);print(num2)
num1 = num1+num2 # assignment 
print("addition is = ",num1)
num1 +=num2
print("addition is = ",num1)
num1 = num1- num2 # assignment 
print("sub is = ",num1)
num1 -=num2
print("sub is = ",num1)
num1 = num1*num2 # assignment 
print("mul is = ",num1)
num1 *=num2
print("mul is = ",num1)
num1 = num1/num2 # assignment 
print("div is = ",num1)
num1 /=num2
print("div is = ",num1)
num1 = num1**num2 # assignment 
print("pow is = ",num1)
num1 **=num2
print("pow is = ",num1)
num1 = num1//num2 # assignment 
print("addition is = ",num1)
num1 //=num2
print("addition is = ",num1)
